name: 自动化质量保障
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-check-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装项目依赖与检测工具
        run: pip install click flake8 pytest

      - name: 静态代码规范检测
        run: flake8 . --max-line-length=120 --count --select=E9,F63,F7,F82 --show-source

      - name: CLI自动化功能测试
        run: |
          python cli.py version
          python cli.py pass_gen -l 12
          python cli.py time_conv